AccountingSolution/TelerikPortal/Controllers/BillController.cs
using System.Linq;
using System.Web.Mvc;
using BLL;
using Bll.Contracts;
using Model;
using TelerikPortal.VM;

namespace TelerikPortal.Controllers
{
    public class BillController : Controller
    {
        private readonly IBillBll<Bill_Header, Bill_Details> _billBll;
        public BillController()
        {
            _billBll = new BillBll();
        }

        // GET: Bill
        public ActionResult GetAllBillsHeaders()
        {
            var billsHeaders = _billBll.GetBillHeaders();       
            return View(billsHeaders);
        }

        [HttpGet]
        public ActionResult CreateHeader()
        {
            var customers = new CustomerBll().GetAll();
            var payments = new PaymentBll().GetAll();

            var billHeaderCVM = new BillHeaderCVM();
            if (customers != null)
            {                
                var customersList = customers.Select(f => new SelectListItem {Value = f.Id,Text = f.Name});
                billHeaderCVM.Customers = customersList;
            }
            if (payments != null)
            {
                var paymentsList = payments.Select(f => new SelectListItem { Value = f.Id, Text = f.Name });
                billHeaderCVM.Payments = paymentsList;
            }
            return View(billHeaderCVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateHeader(BillHeaderCVM billHeaderModel)
        {
            if (ModelState.IsValid == false) return View(billHeaderModel);
            var billHeader = new Bill_Header()
            {                
                CustomerId = billHeaderModel.SelectedCustomerId,
                Discount = billHeaderModel.Discount,
                PaymentId = billHeaderModel.SelectedPaymentId
            };
            _billBll.AddBillHeader(billHeader);
            return RedirectToAction("GetAllBillsHeaders");
        }

        public ActionResult GetAllBillDetails(string billId)
        {
            var billHeader = _billBll.GetBillHeader(billId);
            return billHeader != null ? View(billHeader.Bill_Details) : View();
        }
    }
}

AccountingSolution/TelerikPortal/Controllers/CustomerController.cs
using System.Linq;
using System.Web.Mvc;
using BLL;
using Bll.Contracts;
using Model;

namespace TelerikPortal.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerBll<Customer> _customerBll;
        public CustomerController()
        {
            _customerBll = new CustomerBll();
        }

        // GET: Customer
        public ActionResult GetAll()
        {
            var customers = _customerBll.GetAll();
            return View(customers);
        }

        [HttpGet]
        public JsonResult GetAllJson()
        {
            var customers = _customerBll.GetAll();
            return Json(customers.Select(c => new { Name = c.Name, ID = c.Id }), JsonRequestBehavior.AllowGet);            
        }

        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Customer modelCustomer)
        {
            if (ModelState.IsValid == false) return View(modelCustomer);
            _customerBll.AddCustomer(modelCustomer);
            return RedirectToAction("GetAll");
        }
    }
}

AccountingSolution/TelerikPortal/Controllers/HomeController.cs
using System.Web.Mvc;

namespace TelerikPortal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Welcome to ASP.NET MVC!";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AccountingSolution/TelerikPortal/Controllers/ItemController.cs
using System.Web.Mvc;
using BLL;
using Bll.Contracts;
using Model;

namespace TelerikPortal.Controllers
{
    public class ItemController : Controller
    {
        private readonly IItemBll<Item> _itemBll;
        public ItemController()
        {
            _itemBll = new ItemBll();
        }
        
        public ActionResult GetAll()
        {
            var orderdItems = _itemBll.GetAll();
            return View(orderdItems);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Item modelItem)
        {
            if (ModelState.IsValid == false) return View(modelItem);

            _itemBll.AddItem(modelItem);
            return RedirectToAction("GetAll");
        }
    }
}

AccountingSolution/TelerikPortal/Controllers/PaymentModeController.cs
using System.Web.Mvc;
using BLL;
using Bll.Contracts;
using Model;

namespace TelerikPortal.Controllers
{
    public class PaymentModeController : Controller
    {
        private readonly IPaymentBll<PaymentMode> _paymentBll;
        public PaymentModeController()
        {
            _paymentBll = new PaymentBll();
        }

        // GET: PaymentMode
        public ActionResult GetAll()
        {
            var orderdPaymentModes = _paymentBll.GetAll();
            return View(orderdPaymentModes);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PaymentMode modelPaymentMode)
        {
            if (ModelState.IsValid == false) return View(modelPaymentMode);

            _paymentBll.AddPayment(modelPaymentMode);
            return RedirectToAction("GetAll");
        }
    }
}

AccountingSolution/TelerikPortal/Views/Bill/CreateHeader.cshtml
@model TelerikPortal.VM.BillHeaderCVM

@{
    ViewBag.Title = "CreateHeader";
}

<h2>Create Bill Header</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedCustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectedCustomerId, Model.Customers)
                @Html.ValidationMessageFor(model => model.SelectedCustomerId, "", new { @class = "text-danger" })
            </div>
        </div>
        <br/>
        <div class="form-group">
            @Html.LabelFor(model => model.SelectedPaymentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectedPaymentId, Model.Payments)
                @Html.ValidationMessageFor(model => model.SelectedPaymentId, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.Discount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">                
                @Html.Kendo().TextBoxFor(model => model.Discount)              
                @Html.ValidationMessageFor(model => model.Discount, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <br />
    <br />
    
    @Html.ActionLink("All bills", "GetAllBillsHeaders")
</div>

AccountingSolution/TelerikPortal/Views/Bill/GetAllBillDetails.cshtml
@model Model.Bill_Details

@{
    ViewBag.Title = "GetAllBillDetails";
}

<h2>Bill Details</h2>

<br/>
<br/>
<p>
    @Html.ActionLink("Create New", "CreateDetails")
</p>
<div>
    <h4>Bill_Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BillId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AccountingSolution/TelerikPortal/Views/Bill/GetAllBillsHeaders.cshtml
@using Common
@model IList<Model.Bill_Header>

@{
    ViewBag.Title = "All Bills";
    var haveBills = false;
}

<h2>All Bills</h2>

<p>
    @Html.ActionLink("Create New", "CreateHeader")
</p>
<table  class="table table-striped table-bordered" width="70%">
    <thead>
        <tr>            
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().Id)</th>            
            <th>@Html.DisplayNameFor(model => model.FirstOrDefault().BillDate)</th>
            <th>Customer Name</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.NotEmpty())
        {
            haveBills = true;
                foreach (var bill in Model)
                {                    
                    <tr>
                        <td>
                            @bill.Id
                        </td>
                        <td>
                            @bill.BillDate
                        </td>
                        <td>
                            @bill.Customer.Name
                        </td>
                        <td>
                            @Html.ActionLink("Details", "GetAllBillDetails", "Bill", new { billId = bill.Id }, new { @class = "btn btn-link" })
                             
                        </td>
                    </tr>
                }
        }
        @if (haveBills == false)
        {
            <tr>
                <td>There is no data.</td>
                <td></td>
            </tr>
        }
    </tbody>
</table>            

                                                                    

@*@section scripts
{
    <script type="text/javascript" src="~/Scripts/kendo/2015.3.1111/kendo.grid.min.js"></script>
    <script type="text/javascript" src="~/Scripts/kendo/2015.3.1111/kendo.grid.min.js.map"></script>
}*@

AccountingSolution/TelerikPortal/Views/Customer/Create.cshtml
@model Model.Customer

@{
    ViewBag.Title = "Add new customer";
}

<h2>Add new customer</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AccountingSolution/TelerikPortal/Views/Customer/GetAll.cshtml
@model IEnumerable<Model.Customer>

@{
    ViewBag.Title = "Customers";
}

<h2>Customers</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@(Html.Kendo().Grid(Model)
    .Name("Grid")
    .Columns(columns =>
    {
        columns.Bound(p => p.Name).Title("Customer Name").Width(130);
    })
    .Pageable()
    .Sortable()
    .Scrollable(scr => scr.Height(430))
    .Filterable()
    .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(20)
        .ServerOperation(false)
     )
)

AccountingSolution/TelerikPortal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Telerik UI for ASP.NET MVC TreeView</h3>
    <p>
        Use this area to provide additional information.
    </p>

    @(Html.Kendo().TreeView()
        .Name("LinksTreeView")
        .Items(items =>
        {
            items.Add()
                .Text("Home")
                .Action("Index", "Home");
            items.Add()
                .Text("About")
                .Action("About", "Home");
            items.Add()
                .Text("Contact")
                .Action("Contact", "Home");
        })
    )

</aside>

AccountingSolution/TelerikPortal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<h3>Telerik UI for ASP.NET MVC TabStrip</h3>
<br />

    @(Html.Kendo().TabStrip()
        .Name("ContactsTabStrip")
        .Items(items =>
        {
            items.Add()
                .Text("Phone")
                .Selected(true)
                .Content(@<text>
                    <p>
                        <span class="label">Main:</span>
                        <span>425.555.0100</span>
                    </p>
                    <p>
                        <span class="label">After Hours:</span>
                        <span>425.555.0199</span>
                    </p>
                </text>)
                .ContentHtmlAttributes(new { style = "min-height: 200px" });
            items.Add()
                .Text("Email")
                .Content(@<text>
                    <p>
                        <span class="label">Support:</span>
                        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
                    </p>
                    <p>
                        <span class="label">Marketing:</span>
                        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
                    </p>
                    <p>
                        <span class="label">General:</span>
                        <span><a href="mailto:General@example.com">General@example.com</a></span>
                    </p>
                </text>)
                .ContentHtmlAttributes(new { style = "min-height: 200px" });
            items.Add()
                .Text("Address")
                .Content(@<text>
                    <p>
                        One Microsoft Way<br />
                        Redmond, WA 98052-6399
                    </p>
                </text>)
                .ContentHtmlAttributes(new { style = "min-height: 200px" });
        })
    )

AccountingSolution/TelerikPortal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="jumbotron">
    <h1>Accounting</h1>
    <p class="lead">A simple website using ASP.Net MVC, cshtml, CSS and JavaScript.</p>
    @*<p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
</div>

<br/>
<br />
<br />

<h3>Telerik UI for ASP.NET MVC PanelBar</h3>
<br />

<div class="row">
    <div class="col-md-4">
        <h2>Items</h2>
        <p>@Html.ActionLink("Manage Items", "GetAll", "Item", null, new { @class = "btn btn-default" })</p>        
    </div>
    <div class="col-md-4">
        <h2>Payment Methods</h2>        
        <p>@Html.ActionLink("Manage Payment Modes", "GetAll", "PaymentMode", null, new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <h2>Customers</h2>
        <p>@Html.ActionLink("Manage Customers", "GetAll", "Customer", null, new { @class = "btn btn-default" })</p>        
    </div>
    <div class="col-md-4">
        <h2>Bills</h2>
        <p>@Html.ActionLink("Manage Bills", "GetAllBillsHeaders", "Bill", null, new { @class = "btn btn-default" })</p>
    </div>
</div>

AccountingSolution/TelerikPortal/Views/Item/Create.cshtml
@model Model.Item

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AccountingSolution/TelerikPortal/Views/Item/GetAll.cshtml
@model IEnumerable<Model.Item>

@{
    ViewBag.Title = "GetAll";
}

<h2>Items</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>

@(Html.Kendo().Grid(Model)
    .Name("Grid")
    .Columns(columns =>
    {        
        columns.Bound(p => p.Name).Title("Item Name").Width(130);        
    })
    .Pageable()
    .Sortable()
    .Scrollable(scr => scr.Height(430))
    .Filterable()
    .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(20)
        .ServerOperation(false)
     )
)

AccountingSolution/TelerikPortal/Views/PaymentMode/Create.cshtml
@model Model.PaymentMode

@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add new Payment Mode</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AccountingSolution/TelerikPortal/Views/PaymentMode/GetAll.cshtml
@model IEnumerable<Model.PaymentMode>

@{
    ViewBag.Title = "Payment Modes";
}

<h2>Payment Methods</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@(Html.Kendo().Grid(Model)
    .Name("Grid")
    .Columns(columns =>
    {
        columns.Bound(p => p.Name).Title("Payment Name").Width(130);
    })
    .Pageable()
    .Sortable()
    .Scrollable(scr => scr.Height(430))
    .Filterable()
    .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(20)
        .ServerOperation(false)
     )
)

AccountingSolution/TelerikPortal/Views/Shared/EditorTemplates/Currency.cshtml
@model decimal?

@(Html.Kendo().CurrencyTextBoxFor(m => m)      
      .HtmlAttributes(new {style="width:100%"})
      .Min(0)
)

AccountingSolution/TelerikPortal/Views/Shared/EditorTemplates/Date.cshtml
@model DateTime?

@(Html.Kendo().DatePickerFor(m => m))

AccountingSolution/TelerikPortal/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime?

@(Html.Kendo().DateTimePickerFor(m => m))

AccountingSolution/TelerikPortal/Views/Shared/EditorTemplates/Email.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox" })

AccountingSolution/TelerikPortal/Views/Shared/EditorTemplates/EmailAddress.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="email" })

AccountingSolution/TelerikPortal/Views/Shared/EditorTemplates/GridForeignKey.cshtml
@model object
           
@(
 Html.Kendo().DropDownListFor(m => m)        
        .BindTo((SelectList)ViewData[ViewData.TemplateInfo.GetFullHtmlFieldName("") + "_Data"])
)

AccountingSolution/TelerikPortal/Views/Shared/EditorTemplates/Integer.cshtml
@model int?

@(Html.Kendo().IntegerTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%" })
      .Min(int.MinValue)
      .Max(int.MaxValue)
)

AccountingSolution/TelerikPortal/Views/Shared/EditorTemplates/Number.cshtml
@model double?

@(Html.Kendo().NumericTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%" })
)

AccountingSolution/TelerikPortal/Views/Shared/EditorTemplates/Password.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="password" })

AccountingSolution/TelerikPortal/Views/Shared/EditorTemplates/String.cshtml
@model object 

@Html.Kendo().TextBoxFor(model => model)

AccountingSolution/TelerikPortal/Views/Shared/EditorTemplates/Time.cshtml
@model DateTime?
           
@(Html.Kendo().TimePickerFor(m => m))

AccountingSolution/TelerikPortal/Views/Shared/EditorTemplates/Url.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="url" })

AccountingSolution/TelerikPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>@ViewBag.Title - My Telerik MVC Application</title>
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    	<link href="@Url.Content("~/Content/kendo/2015.3.1111/kendo.common.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2015.3.1111/kendo.mobile.all.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2015.3.1111/kendo.dataviz.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2015.3.1111/kendo.default.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2015.3.1111/kendo.dataviz.default.min.css")" rel="stylesheet" type="text/css" />
    @Scripts.Render("~/bundles/kendo/main")       
</head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-right">
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>

        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My Telerik MVC Application</p>
                </div>
            </div>
        </footer>
        
        @Scripts.Render("~/bundles/jquery")
        @*@Scripts.Render("~/bundles/kendo/all")*@
        @Scripts.Render("~/bundles/jqueryvalidate")
        @RenderSection("scripts", required: false)
    </body>
</html>